import { ClassColors } from "./ClassColors";

export default new Map<string, any>([
    ["Protection", ClassColors.Warrior],
    ["Protection1", ClassColors.Paladin],
    ["Guardian", ClassColors.Druid],
    ["Restoration", ClassColors.Druid],
    ["Holy1", ClassColors.Paladin],
    ["Restoration1", ClassColors.Shaman],
    ["Balance", ClassColors.Druid],
    ["Beastmastery", ClassColors.Hunter],
    ["Marksman", ClassColors.Hunter],
    ["Survival", ClassColors.Hunter],
    ["Arcane", ClassColors.Mage],
    ["Fire", ClassColors.Mage],
    ["Frost", ClassColors.Mage],
    ["Affliction", ClassColors.Warlock],
    ["Demonology", ClassColors.Warlock],
    ["Destruction", ClassColors.Warlock],
    ["Elemental", ClassColors.Shaman],
    ["Arms", ClassColors.Warrior],
    ["Fury", ClassColors.Warrior],
    ["Feral", ClassColors.Druid],
    ["Retribution", ClassColors.Paladin],
    ["Assassination", ClassColors.Rogue],
    ["Sublety", ClassColors.Rogue],
    ["Combat", ClassColors.Rogue],
    ["Enhancement", ClassColors.Shaman],
    ["Holy", ClassColors.Priest],
]);
